import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/layout";
import BannerHome from "../components/home/banner";
import About from "../components/home/about";
import Projects from "../components/home/projects";
import Contact from "../components/home/contact";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Home 🏡</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <BannerHome></BannerHome>
          <About></About>
          <Projects></Projects>
          <Contact></Contact>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </Layout>
  );
}
